builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: "arm64"
brews:
  - repository:
      owner: meringu
      name: terraform-bucket-registry
    commit_author:
      name: Henry Muru Paenga
      email: meringu@gmail.com
    folder: Formula
    homepage: "https://github.com/meringu/terraform-bucket-registry"
