# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformBucketRegistry < Formula
  desc ""
  homepage "https://github.com/meringu/terraform-bucket-registry"
  version "0.2.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meringu/terraform-bucket-registry/releases/download/v0.2.3/terraform-bucket-registry_0.2.3_darwin_amd64.tar.gz"
      sha256 "3a668a1414f8b62c0ad2b61f33ad2447fb56742d8775f76197cfcf99b7fb1c8f"

      def install
        bin.install "terraform-bucket-registry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meringu/terraform-bucket-registry/releases/download/v0.2.3/terraform-bucket-registry_0.2.3_darwin_arm64.tar.gz"
      sha256 "cc97c6c475bc0f5017e16eb48e3e8158952b6bc3fe516759196544a587565dd8"

      def install
        bin.install "terraform-bucket-registry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meringu/terraform-bucket-registry/releases/download/v0.2.3/terraform-bucket-registry_0.2.3_linux_arm64.tar.gz"
      sha256 "0d609ebdce96a9c600269e755dc0268c5a83eab7a53b04a3ec7c73e08a00e987"

      def install
        bin.install "terraform-bucket-registry"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/meringu/terraform-bucket-registry/releases/download/v0.2.3/terraform-bucket-registry_0.2.3_linux_armv6.tar.gz"
      sha256 "a79abc9547a82544d912cbf2ee4996de4e497d7e727254b442ba0ba70cb71542"

      def install
        bin.install "terraform-bucket-registry"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/meringu/terraform-bucket-registry/releases/download/v0.2.3/terraform-bucket-registry_0.2.3_linux_amd64.tar.gz"
      sha256 "5c1c7e25207613682b7cfcfc23545230272ff3627f1c066aaa3e5199a3bb0734"

      def install
        bin.install "terraform-bucket-registry"
      end
    end
  end
end
