# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformBucketRegistry < Formula
  desc ""
  homepage "https://github.com/meringu/terraform-bucket-registry"
  version "0.1.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/meringu/terraform-bucket-registry/releases/download/v0.1.0/terraform-bucket-registry_0.1.0_darwin_amd64.tar.gz"
    sha256 "fe06022a9829fed00d59301b8ed1e8bc78fb030bcdc4d5c4762cd1d6134a0ffc"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/meringu/terraform-bucket-registry/releases/download/v0.1.0/terraform-bucket-registry_0.1.0_darwin_arm64.tar.gz"
    sha256 "b167830dd76fb5e33b0c6d4471aa2775ecc87c8b4c3049dacb78ed94a8a4b52a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/meringu/terraform-bucket-registry/releases/download/v0.1.0/terraform-bucket-registry_0.1.0_linux_amd64.tar.gz"
    sha256 "b8f9cc5d5e79bbc4fb695ee752938456c20f312394f01d521f95c3768fb065fd"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/meringu/terraform-bucket-registry/releases/download/v0.1.0/terraform-bucket-registry_0.1.0_linux_armv6.tar.gz"
    sha256 "dd42ffc9f6a59bc52efab05b7ba019511269c80848a90eebd41c63eca062c10c"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/meringu/terraform-bucket-registry/releases/download/v0.1.0/terraform-bucket-registry_0.1.0_linux_arm64.tar.gz"
    sha256 "64166a6412ba2119662660a791dd98242ad211a0bf3a8512bb79ac27cd65cb7e"
  end

  def install
    bin.install "terraform-bucket-registry"
  end
end
